debug=true
oauth.consumerKey=DK4XfvLy7ZGnhwWIaDAerJEkN
oauth.consumerSecret=lMGO3GdecvRecr6W1AmtMlfQ0ZNikoAF9fRBNEPTV1mFkBXx31
oauth.accessToken=1982082292727349248-SyNiEMJgYxFwwsOgoC6brWUbsYNriY
oauth.accessTokenSecret=OthhpaeL6u51em6YZx6vHsNOFtaIX7iQhH1In4aGjjGff